### ISSUE TITLE
Headings are still added to the TOC

### ISSUE THREAD

**Issue by jeroenkruis** [mauvm/documark-chapter-numbering#3]
Headings are still added to the TOC when .no-index has been added to the chapter itself. They don't appear in the TOC in the document itself which is good, but the integrated TOC in the PDF reader still shows the headings.

![screen shot 2015-03-26 at 11 47 36](https://cloud.githubusercontent.com/assets/1212674/6844749/ea5bffca-d3ad-11e4-8448-a92152f3603b.png)

.no-index should include functionality that excludes them from both the TOC of the document and the one that the PDF reader generates.

Tested in Apple Preview 8.0

**Comment by mauvm** [comment]
This is an issue with the [dmp-table-of-contents](https://github.com/documark/dmp-table-of-contents) plugin, since this plugin only does chapter numbering. Please try version 0.4.0 of that plugin, which updates the index in the plugin code rather than injecting a script that does it on PDF compile time. That should fix the issue!
